stages:
  - test
  - build
  - publish

image: python:latest

test-application:
  stage: test
  script:
    - echo Faut écrire des tests

build-application:
  stage: build
  script:
    - python setup.py sdist bdist_wheel
  only:
    - tags

publish-application:
  stage: publish
  script:
    - pip install twine
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  only:
    - tags
